- name: Creating an EC2 instance
  hosts: local
  connection: local


  tasks:
    - name: create EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        instance_type: t2.micro
        region: ap-south-1a
        security_group: default
        network:
          image_id: "{{ item.image }}"
          public_ip_address: true

        tags:
          Environment: production


  loop:
    - { name: 'ubuntu-1' , image: 'id-ert465756' }
    - { name: 'ubuntu-2' , image: 'id-ertyui762e'}
    - { name: 'centos' , image: 'id-456ertgggggg'}
